# Copyright 2026 Anthropic PBC
# SPDX-License-Identifier: Apache-2.0

"""``RouteDoc``: one 线路 as a structured document, the static half of the catalog.

The ERP sells a 线路 by name, tags and a Word or PDF attachment; the attachment is where the
product actually is — the flights, the day-by-day programme, the hotels, the meals, what the
price includes and what it does not. ``RouteDoc`` is that attachment read into fields, so the
search can filter on what a line really contains and the cards can show it, while the 团期,
seats and prices stay the ERP's and are read live (``docs/route-doc.md``).

A document is evidence read by a parser, never a schema the agency wrote to, so every one
carries ``source`` (which attachment, which ETag, which parser) and ``quality`` (a completeness
score and the fields a person should look at). The agency's product staff review the flagged
ones; nothing here is published to a customer page before that.

``data/route-schema.json`` is this model's JSON Schema, regenerated by
``scripts/parse_attachments.py --schema`` and held to the model by ``tests/test_route_doc.py``."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

SCHEMA_VERSION = "1.0"


class _Doc(BaseModel):
    model_config = ConfigDict(extra="forbid")


class Flight(_Doc):
    """One flight segment as the attachment writes it (参考航班 MU6017 上海浦东-科伦坡 1425-1900).
    Times are kept as written — an attachment states 夏令时/冬令时 pairs and ``+1`` days — and
    ``day`` is the itinerary day the segment is on."""

    day: int
    flight_no: str = ""
    carrier: str = ""
    from_place: str = ""
    to_place: str = ""
    times: str = ""
    raw: str


class Sight(_Doc):
    """One named stop of a day: a 【景点】, a 购物店, a 自费项目 or a 赠送 item. ``kind`` is
    what the words around it say; ``ticket_included`` is True on 含门票/入内, False on 外观,
    None where the text says neither."""

    name: str
    kind: Literal["景点", "外观", "购物", "自费", "赠送", "自由活动"] = "景点"
    duration: str = ""
    ticket_included: bool | None = None


class Meal(_Doc):
    """One meal: the text as written and whether the price includes it (X, ×, 自理 and an
    empty cell all mean it does not)."""

    text: str = ""
    included: bool | None = None


class Meals(_Doc):
    breakfast: Meal = Field(default_factory=Meal)
    lunch: Meal = Field(default_factory=Meal)
    dinner: Meal = Field(default_factory=Meal)


class Hotel(_Doc):
    """The night's 住宿: the names as written (several alternatives joined by ``/``), whether
    the attachment says 或同级, and the standard where a grade is stated on the line."""

    name: str
    or_similar: bool = False
    grade: str = ""


class Day(_Doc):
    """One itinerary day. ``places`` is the title's A-B-C route; ``distances_km`` the KM
    figures written between them; ``transport`` the 车程/交通 notes; ``text`` the programme
    as written, kept whole because the parsed fields are a reading of it and not a
    replacement."""

    day: int
    title: str
    places: list[str] = Field(default_factory=list)
    distances_km: list[int] = Field(default_factory=list)
    transport: str = ""
    overnight: Literal["hotel", "flight", "home", "unknown"] = "unknown"
    flights: list[Flight] = Field(default_factory=list)
    sights: list[Sight] = Field(default_factory=list)
    meals: Meals = Field(default_factory=Meals)
    hotel: Hotel | None = None
    text: str = ""


class ShoppingStop(_Doc):
    name: str
    day: int | None = None
    duration: str = ""


class OptionalItem(_Doc):
    """A 自费项目 with the price as written (``120 美金/人``)."""

    name: str
    price: str = ""
    day: int | None = None


class Policies(_Doc):
    """What the terms say about money and paperwork, each the sentence as written."""

    single_room: str = ""
    child: str = ""
    visa: str = ""
    cancellation: str = ""
    deposit: str = ""


class Summary(_Doc):
    days: int
    nights: int | None = None
    depart_city: str = ""
    countries: list[str] = Field(default_factory=list)
    region: str = ""


class Cover(_Doc):
    """The attachment's front matter: the labelled rows (航空公司, 酒店标准, 用餐安排, 吃/住/行)
    and the ★ highlights, as written."""

    airline: str = ""
    hotel_standard: str = ""
    meal_standard: str = ""
    highlights: list[str] = Field(default_factory=list)
    fields: dict[str, str] = Field(default_factory=dict)


class Source(_Doc):
    attachment_name: str
    attachment_url: str
    etag: str | None = None
    bytes: int
    parsed_at: datetime
    parser: str


class Quality(_Doc):
    """``completeness`` is the parser's own score in [0, 1] (``route_parser.score``);
    ``needs_review`` names what a person should check, in the reviewer's language;
    ``reviewed_by``/``reviewed_at`` are set by the reviewer, never by the parser."""

    completeness: float = Field(ge=0, le=1)
    needs_review: list[str] = Field(default_factory=list)
    reviewed_by: str = ""
    reviewed_at: datetime | None = None


class RouteDoc(_Doc):
    """One 线路 as its attachment describes it. Identity and the fields the ERP itself states
    come from the catalog record; everything under ``cover``, ``days`` and the terms comes
    from the attachment."""

    schema_version: str = SCHEMA_VERSION
    route_id: int
    route_code: str
    name: str
    department: str
    sale_type: str = ""
    summary: Summary
    cover: Cover = Field(default_factory=Cover)
    transport: list[Flight] = Field(default_factory=list)
    days: list[Day] = Field(default_factory=list)
    inclusions: list[str] = Field(default_factory=list)
    exclusions: list[str] = Field(default_factory=list)
    shopping: list[ShoppingStop] = Field(default_factory=list)
    optional: list[OptionalItem] = Field(default_factory=list)
    policies: Policies = Field(default_factory=Policies)
    notices: list[str] = Field(default_factory=list)
    source: Source
    quality: Quality


def json_schema() -> dict:
    """The JSON Schema the agency's product staff and the review tooling read."""
    schema = RouteDoc.model_json_schema()
    schema["title"] = "RouteDoc"
    schema["$comment"] = (
        f"schema_version {SCHEMA_VERSION}; one 线路 as its 行程附件 describes it, parsed by "
        "examples/tour/api/route_parser.py. Fields under source and quality are the parser's own."
    )
    return schema
