"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import {WarehouseClient,message} from "../lib/api";

type Inquiry={id:string;question:string;context:{route_name:string;window:{start:string;end:string}|null;party:{adults:number|null;children:number|null;child_ages:number[]|null};rooms:Record<string,unknown>|null};status:string;created_at:string;replies:{id:string;answer:string;created_at:string}[]};
export function Inquiries({api,writable}:{api:WarehouseClient;writable:boolean}){
  const [items,setItems]=useState<Inquiry[]>([]),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async(signal?:AbortSignal)=>{try{const p=await api.get<{items:Inquiry[];next_cursor:string|null}>("/copilot/inquiries",signal);if(!signal?.aborted){setItems(p.items);setCursor(p.next_cursor);setError("");}}catch(e){if(!signal?.aborted){setError(message(e));setItems([]);}}},[api]);
  useEffect(()=>{const abort=new AbortController();void load(abort.signal);const refresh=()=>{if(document.visibilityState==="visible")void load(abort.signal);};const timer=setInterval(refresh,15000);window.addEventListener("focus",refresh);return()=>{abort.abort();clearInterval(timer);window.removeEventListener("focus",refresh);};},[load]);
  async function reply(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);setError("");try{await api.post(`/copilot/inquiries/${id}/replies`,{request_id:crypto.randomUUID(),answer:data.get("answer")});form.reset();setNotice("回复已送达顾问。顾问核对采纳后用于本次跟单。");await load();}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <section className="stack"><header className="section-head"><div><h2>顾问核实单</h2><p className="muted">核对顾问提交的问题，回复只用于对应跟单，不会修改全局价表、行程或库存。</p></div><button onClick={()=>void load()}>刷新</button></header>{error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{!items.length&&!error&&<div className="empty">暂无顾问提交的核实问题。</div>}{items.map(i=><article className="panel" key={i.id} style={{padding:24,marginBottom:20}}><div className="section-head"><h3>{i.context.route_name}</h3><span className={`badge ${i.status==="replied"?"good":"warn"}`}>{i.status==="adopted"?"顾问已采纳":i.status==="replied"?"已回复":"待核实"}</span></div><p className="muted">出发范围：{i.context.window?`${i.context.window.start} 至 ${i.context.window.end}`:"待确认"} · 成人 {i.context.party.adults??"待确认"} / 儿童 {i.context.party.children??"待确认"}{i.context.party.child_ages?.length?` · 儿童年龄 ${i.context.party.child_ages.join("、")}`:""}</p><h3 style={{margin:"20px 0",whiteSpace:"pre-wrap"}}>{i.question}</h3>{i.replies.map(r=><div className="notice" key={r.id}><b>已发给顾问的回复</b><p style={{whiteSpace:"pre-wrap"}}>{r.answer}</p><small>{new Date(r.created_at).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"})}（北京时间）</small></div>)}{writable?<form onSubmit={e=>reply(e,i.id)} style={{display:"grid",gap:12,marginTop:18}}><label>核实结果与适用条件<textarea name="answer" aria-label="核实结果与适用条件" maxLength={4000} required rows={4} placeholder="请注明确定的事实、适用范围，以及仍需顾问确认的事项。" style={{display:"block",width:"100%",marginTop:8}}/></label><label style={{display:"flex",gap:8}}><input type="checkbox" required/>我已核对，本回复将提交给该顾问</label><button className="primary" disabled={busy}>{busy?"正在提交…":"发送核实回复"}</button></form>:<p className="muted">当前角色仅可查看核实单。</p>}</article>)}{cursor&&<button onClick={async()=>{try{const p=await api.get<{items:Inquiry[];next_cursor:string|null}>(`/copilot/inquiries?before=${cursor}`);setItems(v=>[...v,...p.items]);setCursor(p.next_cursor);}catch(e){setError(message(e));}}}>加载更多核实单</button>}</section>;
}
