"use client";
import {useEffect,useState} from "react";
import schema from "web-shared/route-kit-schema.json";
import {useRouteCover} from "web-shared/route-cover";
import {RouteDetail} from "web-shared/route-detail";
import {WarehouseClient,message} from "../lib/api";
import {DocumentEvidence} from "./documents";
import {Field} from "./common";

type Row=Record<string,any>;
const clone=(x:Row)=>structuredClone(x);
const names:Record<string,string>={title:"标题",subtitle:"副标题",days_count:"行程天数",nights:"住宿晚数",depart_city:"出发地",countries:"到访国家",cities:"到访城市",day:"日序",day_end:"连续日期结束日",summary:"当天简述",travel_text:"参考里程与车程",items:"行程节点",name:"名称",local_name:"当地名称",description:"说明",type:"节点类型",visit_mode:"游览方式",ticket:"门票",inclusion:"是否包含",duration_text:"参考时长",price_text:"附件费用",min_participants:"项目最低人数",booking_note:"预约说明",includes:"包含内容",children:"子项目",alternative:"替代安排",disclaimer:"限制条件",extra_cost_note:"另付费用",condition:"适用条件",text:"正文",meals:"三餐",breakfast:"早餐",lunch:"午餐",dinner:"晚餐",stay:"住宿",kind:"类型",names:"酒店名称",city:"城市",grade_text:"住宿标准",grade_basis:"标准依据",or_similar:"或同级",check_in_text:"入住说明",room_type:"房型",consecutive_nights:"连住晚数",status:"状态",notes:"当日提示",transport:"交通",mode:"交通类型",from_place:"出发地",to_place:"目的地",distance_text:"里程",service_no:"航班或车次",times_text:"参考起降时间",reference:"参考班次",departure_local_time:"当地出发时间",arrival_local_time:"当地到达时间",arrival_day_offset:"到达跨日数",clock_text:"参考时间",part_of_day:"时段",highlight:"特别安排",spot_label:"原文机位标识",shopping_kind:"购物类别",categories:"品类",services:"用车与导游",coach:"用车",guide:"导游",note:"说明",port_call:"邮轮靠港",port:"港口",arrive_text:"到港",depart_text:"离港",all_aboard_text:"最迟返船",day_kind:"行程日类型",cover_facts:"吃住行概览",selling_points:"卖点标签",highlights:"行程亮点",prices:"附件参考价格",label:"价格名称",amount:"金额",currency:"币种",basis:"计价单位",audience:"适用人群",category:"分类",inclusions:"费用包含",exclusions:"费用不含",shopping:"购物点",optional_items:"自费项目",policies:"费用与退改",single_room:"单房差",child:"儿童",senior:"老人",tips:"服务费",cancellation:"退改",deposit:"定金",notices:"温馨提示",applicability:"行程适用范围",start:"适用开始日期",end:"适用结束日期",departure_cities:"适用出发城市",version_label:"版本名称",formation:"成团要求",minimum_travelers:"最低成团人数",failure_action:"不成团处理",booking_deadline:"收客截止说明",traveler_requirements:"报名限制",minimum_age:"最低年龄",maximum_age:"最高年龄",bed_policy:"占床要求",conditions:"限制条件",pregnancy:"孕妇",visa:"签证",submission_deadline:"材料截止说明",passport_validity:"护照有效期",insurance:"保险",included:"是否包含",raw:"原文依据",meeting:"集合与联运",location:"地点",time:"时间",domestic_connection:"国内联运",cancellation_tiers:"退改区间",days_before_min:"出发前最少天数",days_before_max:"出发前最多天数",penalty_percent:"扣费比例",penalty_money:"扣费金额",unit:"计费单位",shopping_status:"购物安排状态",reason:"原因"};
const hidden=new Set(["cite","title_cite","shopping_cite","departure_dates_cite","day_id","node_id","units","overview_units","issues","auto","review"]);
const enumNames:Record<string,string>={hotel:"酒店",ship:"船上",flight:"航班",train:"列车",home:"回家",self:"自理",not_applicable:"不适用",morning:"上午",noon:"中午",afternoon:"下午",evening:"傍晚",night:"夜间",coach:"巴士",night_train:"夜车",ferry:"渡轮",cruise:"邮轮",boat:"游船",speedboat:"快艇",seaplane:"水上飞机",shuttle:"接驳车",cable_car:"缆车",designated_store:"指定购物店",outlet_mall:"奥特莱斯",department_store:"百货商场",market:"市场",tour:"团费",service_fee:"服务费",additional:"另付费用",child:"儿童",senior:"老人",single_room:"单房差",person:"人",room:"间",weather:"天气",wildlife:"野生动物",operating_days:"营业日期",closure:"关闭",booking:"预约",traffic:"交通",other:"其他",partial:"部分包含",unknown:"未说明",inside:"入内",outside:"外观",passing:"途经",drive_by:"乘车游览",distant_view:"远眺",walk:"步行",included:"包含",excluded:"不含",free_entry:"免费",gift:"赠送",optional_paid:"另付费",package_item:"套餐内",recommended_not_included:"推荐·不含",meet:"集合",transport:"交通",poi:"景点",group:"观光段",activity:"活动",free:"自由活动",shopping:"购物",optional:"自费",package:"套餐",recommend:"推荐",photo_spot:"拍照点",notice:"提醒",regular:"常规行程",transit:"交通日",at_sea:"海上日",port_call:"靠港",cruising_no_landing:"不登岸巡游",resort:"度假",supplier_description:"供应商描述",official_rating:"已核验官方评级",present:"含购物安排",none:"明确无购物"};
const node=()=>({node_id:crypto.randomUUID(),type:"poi",name:"",description:"",visit_mode:"unknown",ticket:"unknown",inclusion:"unknown",duration_text:"",includes:[],children:[],cite:[]});
const defs:Row=(schema as Row).$defs;
function resolve(s:Row):Row{return s?.$ref?defs[s.$ref.split("/").pop()]:s??{};}
function fresh(s:Row):any {s=resolve(s);if(s.default!==undefined)return structuredClone(s.default);if(s.anyOf)return fresh(s.anyOf.find((x:Row)=>x.type!=="null")??s.anyOf[0]);if(s.type==="array")return [];if(s.type==="object")return Object.fromEntries(Object.entries(s.properties??{}).map(([k,v])=>[k,k==="node_id"||k==="day_id"?crypto.randomUUID():fresh(v as Row)]));if(s.enum)return s.enum[0];if(s.type==="boolean")return false;if(s.type==="integer"||s.type==="number")return null;return "";}
function Fields({value,name,onChange,shape}:{value:any;name:string;onChange:(x:any)=>void;shape?:Row}) {
  let spec=resolve(shape??(name==="day"?defs.Day:(schema as Row).properties?.[name]));
  const nullable=spec.anyOf?.some((x:Row)=>x.type==="null");
  if(spec.anyOf)spec=resolve(spec.anyOf.find((x:Row)=>x.type!=="null")??spec.anyOf[0]);
  if(value==null&&spec.type==="object")return <div className="row"><span>{names[name]??name}：未提供</span><button className="btn" type="button" onClick={()=>onChange(fresh(spec))}>补充此项</button></div>;
  if(Array.isArray(value))return <fieldset className="panel stack"><legend>{names[name]??name}</legend>{value.map((x,i)=><div className="stack" key={x?.node_id??i}><Fields name={name} value={x} shape={spec.items} onChange={v=>onChange(value.map((z,j)=>i===j?v:z))}/><div className="row"><button className="link" type="button" disabled={!i} onClick={()=>{const a=[...value];[a[i-1],a[i]]=[a[i],a[i-1]];onChange(a);}}>上移</button><button className="link" type="button" onClick={()=>onChange(value.filter((_,j)=>i!==j))}>移除此项</button></div></div>)}<button className="btn" type="button" onClick={()=>onChange([...value,fresh(spec.items??{})])}>＋ 添加{names[name]??"条目"}</button></fieldset>;
  if(value&&typeof value==="object")return <div className="stack">{name!=="day"&&<h4>{names[name]??name}</h4>}{Array.isArray(value.cite)&&<Field label="依据原文编号（在原文对照中查阅）"><input className="input" value={value.cite.join(",")} onChange={e=>{if(/^[0-9,， ]*$/.test(e.target.value))onChange({...value,cite:e.target.value.split(/[,， ]+/).filter(Boolean).map(Number)});}}/></Field>}{Object.entries(value).filter(([k])=>!hidden.has(k)&&!(name==="day"&&k==="status")).map(([k,v])=><Fields key={k} name={k} value={v} shape={spec.properties?.[k]} onChange={next=>onChange({...value,[k]:next})}/>)}{nullable&&<button className="link" type="button" onClick={()=>onChange(null)}>清除此项</button>}</div>;
  if(spec.enum)return <Field label={names[name]??name}><select className="input" value={value??""} onChange={e=>onChange(e.target.value||null)}>{nullable&&<option value="">未说明</option>}{spec.enum.map((x:string)=><option key={x} value={x}>{enumNames[x]??x}</option>)}</select></Field>;
  if(spec.type==="boolean")return <Field label={names[name]??name}><select className="input" value={value==null?"unknown":String(value)} onChange={e=>onChange(e.target.value==="unknown"?null:e.target.value==="true")}>{nullable&&<option value="unknown">未说明</option>}<option value="true">是</option><option value="false">否</option></select></Field>;
  if(spec.type==="integer"||spec.type==="number")return <Field label={names[name]??name}><input className="input" type="number" min={spec.minimum} max={spec.maximum} value={value??""} onChange={e=>onChange(e.target.value===""?null:Number(e.target.value))}/></Field>;
  if(spec.format==="date")return <Field label={names[name]??name}><input className="input" type="date" value={value??""} onChange={e=>onChange(e.target.value||null)}/></Field>;
  return <Field label={names[name]??name}><textarea className="input" rows={String(value??"").length>70?4:2} value={value??""} onChange={e=>onChange(e.target.value)}/></Field>;
}
export function RouteKitEditor({api,id,initial,writable,onProposed}:{api:WarehouseClient;id:string;initial:Row;writable:boolean;onProposed:()=>void}) {
  const [draft,setDraft]=useState(initial),[content,setContent]=useState(clone(initial.content)),[mode,setMode]=useState("read"),[day,setDay]=useState(0),[note,setNote]=useState(initial.source_note??""),[issues,setIssues]=useState<Row[]>(initial.issues??[]),[resolutions,setResolutions]=useState<Row[]>(initial.review_resolutions??[]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[dirty,setDirty]=useState(false),[allowed,setAllowed]=useState(true),[preview,setPreview]=useState<Row|null>(null);
  useEffect(()=>{let stopped=false;const abort=new AbortController();async function check(){try{await api.get(`/merchant/routes/${id}/content`,abort.signal);}catch(e){if(!stopped){setAllowed(false);setContent({});setPreview(null);setResolutions([]);setError(message(e));}}}const timer=setInterval(check,30000);window.addEventListener("focus",check);return()=>{stopped=true;abort.abort();clearInterval(timer);window.removeEventListener("focus",check);};},[api,id]);
  const coverUrl=useRouteCover(api,allowed?(mode==="customer"?preview?.content?.cover_asset_id:content.source?.cover_image):null);
  function edit(next:Row){setContent(next);setDirty(true);setResolutions([]);setNotice("内容已修改，需要重新校验并确认。");}
  async function save(validate=false){setBusy(true);setError("");try{const r=await api.post<Row>(`/merchant/routes/${id}/content${validate?"/validate":""}`,{expected_revision:draft.revision,expected_source_hash:draft.source_hash,source_kind:draft.source_kind,source_note:note,content,review_resolutions:resolutions});setIssues(r.issues);if(!validate){setDraft({...draft,revision:r.revision,revision_id:r.revision_id});setContent(r.content);setDirty(false);setNotice("草稿已保存，尚未发布。");}else setNotice(r.issues.length?"请处理或确认以下问题。":"校验通过，可保存后提交审批。");}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function propose(){setBusy(true);try{await api.post("/route-content-proposals",{target_id:id,revision_id:draft.revision_id,note});onProposed();}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function adopt(){setBusy(true);try{const fresh=await api.get<Row>(`/merchant/routes/${id}/content?include_source=true`);setDraft(fresh);edit(clone(fresh.candidate));setIssues(fresh.issues);setDay(0);}catch(e){setError(message(e));}finally{setBusy(false);}}
  if(!allowed)return <p role="alert" className="notice error">访问权限需要重新确认，请重新进入线路详情。{error}</p>;
  return <section className="stack"><header className="panel stack"><h2>线路内容工作台</h2><p>{draft.published_review_mode==="test_auto"?"测试自动发布 · 未人工审核":"结构化整理稿 · 待人工复核"}　草稿 {draft.revision} 版 / 已发布 {draft.content_version} 版{dirty?" · 有未保存修改":""}</p><div className="row"><button className="btn" onClick={()=>setMode("read")}>阅读与原文对照</button>{writable&&<button className="btn" onClick={()=>setMode("edit")}>整理行程</button>}<button className="btn" onClick={async()=>{try{setPreview(await api.get<Row>(`/merchant/routes/${id}/customer-preview`));setMode("customer");}catch(e){setError(message(e));}}}>已发布客户预览</button></div></header>
    {draft.test_publication&&<section className="panel stack"><h3>测试发布评估</h3><p>有效内容覆盖率 <strong>{draft.test_publication.coverage_percent}%</strong> / 门槛 85%</p><p className="muted">直接引用原文的单元比例；不把推断续句和原样挂入算作整理完成，不代表事实准确率。</p><p>{draft.test_publication.enabled?"测试自动发布已启用":"自动发布未在当前账号启用"} · {draft.test_publication.eligible?"已达到发布门槛":"保留草稿"}</p>{draft.test_publication.blockers?.map((x:Row,i:number)=><p key={i} className="notice warning">{x.message}</p>)}</section>}
    {draft.parsing&&<p className="notice">附件正在处理或需要重试，当前保留上一版内容供对照。</p>}{draft.source_changed&&<p className="notice warning">资料已有新版本，请对照后采用新候选稿。<button disabled={busy||dirty} onClick={adopt}>采用新候选稿</button></p>}
    {error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
    {draft.asset_id&&<DocumentEvidence api={api} asset={draft.asset_id} name={content.source?.file_name} hash={content.source?.sha256} version={draft.asset_product_version} parser={content.source?.parser}/>}
    {mode==="read"&&<RouteDetail content={content} review coverUrl={coverUrl}/>}{mode==="customer"&&(preview?.published?<RouteDetail content={preview.content} coverUrl={coverUrl}/>:<p className="notice">尚无已发布的行程，解析稿不会直接向顾问展示。</p>)}
    {mode==="edit"&&writable&&<fieldset disabled={busy||!!draft.parsing} className="stack document-fieldset"><div className="row"><label>选择日期 <select className="input" value={day} onChange={e=>setDay(Number(e.target.value))}>{content.days.map((d:Row,i:number)=><option key={d.day_id??i} value={i}>D{d.day} · {d.title}</option>)}</select></label><button className="btn" onClick={()=>{const c=clone(content);c.days.push({day_id:crypto.randomUUID(),day:c.days.length+1,day_end:null,title:"",summary:"",cities:[],countries:[],travel_text:"",day_kind:"regular",items:[node()],meals:{breakfast:{status:"unknown",text:"",cite:[]},lunch:{status:"unknown",text:"",cite:[]},dinner:{status:"unknown",text:"",cite:[]}},stay:{kind:"unknown",names:[],city:"",grade_text:"",grade_basis:"unknown",room_type:"",consecutive_nights:null,or_similar:false,check_in_text:"",cite:[]},notes:[],units:[],overview_units:[],status:"extracted",issues:[],title_cite:[]});edit(c);setDay(c.days.length-1);}}>＋ 添加一天</button></div>
      {content.days[day]&&<div className="panel stack"><h3>第 {content.days[day].day} 天</h3><Fields name="day" value={content.days[day]} onChange={value=>{const c=clone(content);c.days[day]=value;edit(c);}}/><button className="link" onClick={()=>{const c=clone(content);c.days.splice(day,1);edit(c);setDay(Math.max(0,day-1));}}>移除此日</button></div>}
      <details className="panel"><summary>线路概览、价格、费用与报名条件</summary><div className="stack">{["title","subtitle","days_count","nights","depart_city","countries","cover_facts","selling_points","highlights","prices","inclusions","exclusions","shopping_status","shopping","optional_items","policies","notices","applicability","formation","traveler_requirements","meeting","cancellation_tiers"].map(k=><Fields key={k} name={k} value={content[k]} onChange={value=>edit({...content,[k]:value})}/>)}</div></details>
      <section className="panel stack"><h3>待处理与待确认事项</h3>{issues.map((item,i)=><div key={i} className="panel"><p>{item.message}</p>{item.acknowledgeable&&<Resolution item={item} confirmed={resolutions.some(r=>r.code===item.code&&r.path===item.path&&r.basis_hash===item.basis_hash)} onConfirm={r=>{setResolutions(old=>[...old.filter(x=>x.code!==r.code||x.path!==r.path),r]);setDirty(true);}}/>}</div>)}{!issues.length&&<p>当前校验通过。</p>}</section>
      <Field label="整理与复核说明"><textarea className="input" value={note} maxLength={2000} onChange={e=>{setNote(e.target.value);setDirty(true);}}/></Field><div className="row"><button className="btn primary" disabled={!note.trim()} onClick={()=>save()}>保存草稿</button><button className="btn" disabled={!note.trim()} onClick={()=>save(true)}>重新校验</button><button className="btn" disabled={dirty||!draft.revision_id||issues.length>0||!note.trim()} onClick={propose}>提交发布审批</button></div><p className="muted">仅写入云仓。人工审批通过后才向顾问展示。</p></fieldset>}
  </section>;
}
function Resolution({item,onConfirm,confirmed}:{item:Row;onConfirm:(r:Row)=>void;confirmed:boolean}){const [note,setNote]=useState("");return <div className="stack"><Field label="对照原文后的处理依据"><input className="input" value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></Field><button className="btn" disabled={!note.trim()||confirmed} onClick={()=>onConfirm({code:item.code,path:item.path,basis_hash:item.basis_hash,note})}>{confirmed?"已记录，保存时复核":"确认此项"}</button></div>;}
