"use client";

import {RouteKitEditor} from "./route-kit-editor";
import {isRouteKit,RouteDetail} from "web-shared/route-detail";
import {useEffect, useState} from "react";
import {WarehouseClient, message, type Change} from "../lib/api";
import {Field, LoadState, useData} from "./common";
import {DocumentContent, DocumentDiff, DailyExtraFields, type RouteContent} from "./document-content";
import {DocumentEvidence} from "./documents";
import {RouteFactReview} from "./route-fact-review";
import {DailyTravel, RouteItinerary, RouteTerms} from "./route-itinerary";

type Row=Record<string,any>;
const clone=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const blockNames:Record<string,string>={programme:"行程说明",transport:"交通",visit:"游览",free_time:"自由活动",shopping:"购物",optional:"自费",notice:"提醒"};
const categories:Record<string,string>={destination:"目的地",theme:"主题",transport:"交通",stay:"住宿",experience:"体验",audience:"人群",other:"其他"};
const blankDay=(day:number)=>({day,day_id:crypto.randomUUID(),title:"",places:[],distances_km:[],travel_reference:"",transport:"",overnight:"unknown",flights:[],sights:[],meals:{breakfast:{text:"",included:null},lunch:{text:"",included:null},dinner:{text:"",included:null}},hotel:null,text:"",summary:"",summary_basis_hash:"",blocks:[]});

export function RouteTags({api,id,writable,onProposed}:{api:WarehouseClient;id:string;writable:boolean;onProposed:()=>void}) {
  const state=useData<Row>(api,`/merchant/routes/${id}/tags`);
  return <section className="panel stack"><div className="row between"><h2>线路标签</h2><span className="muted">标签用于查找线路，行程承诺以发布内容为准</span></div><LoadState {...state}/>{state.data && <TagForm key={`${id}:${state.data.display_version}`} api={api} value={state.data} writable={writable} onProposed={onProposed}/>}</section>;
}
function TagForm({api,value,writable,onProposed}:{api:WarehouseClient;value:Row;writable:boolean;onProposed:()=>void}) {
  const [tags,setTags]=useState<Row[]>(value.tags),[edit,setEdit]=useState<Row|null>(null),[dirty,setDirty]=useState(false),[note,setNote]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const active=tags.filter(t=>t.state==="confirmed");
  const candidates=value.candidates.filter((t:Row)=>!tags.some(v=>v.id===t.id));
  function put(tag:Row){setTags(old=>[...old.filter(t=>t.id!==tag.id),tag]);setDirty(true);setEdit(null);}
  async function submit(){setError("");setBusy(true);try{await api.post("/route-tag-proposals",{target_id:value.target_id,expected_display_version:value.display_version,tags,note});onProposed();}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <><div className="route-tags">{active.map(t=><span className="route-tag" key={t.id}><span>{categories[t.category]} · {t.label}</span>{writable && <><button className="link" aria-label={`修改标签 ${t.label}`} onClick={()=>setEdit(clone(t))}>编辑</button><button className="tag-remove" aria-label={`移除标签 ${t.label}`} onClick={()=>put({...t,state:"excluded"})}>×</button></>}</span>)}{!active.length && <p className="muted">尚无已确认标签。</p>}{writable && <button className="btn" onClick={()=>setEdit({id:crypto.randomUUID(),label:"",source_label:null,category:"theme",state:"confirmed",search_enabled:true,customer_visible:false})}>＋ 新增标签</button>}</div>
    {edit && <form className="route-tag-editor stack" onSubmit={e=>{e.preventDefault();put(edit);}}><div className="row"><Field label="标签文字"><input className="input" value={edit.label} required maxLength={60} onChange={e=>setEdit({...edit,label:e.target.value})}/></Field><Field label="标签类别"><select className="input" value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}>{Object.entries(categories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field></div><label className="check"><input type="checkbox" checked={edit.search_enabled} onChange={e=>setEdit({...edit,search_enabled:e.target.checked})}/>用于顾问搜索</label><label className="check"><input type="checkbox" checked={edit.customer_visible} onChange={e=>setEdit({...edit,customer_visible:e.target.checked})}/>允许客户查看</label><div className="row"><button className="btn primary">保留标签修改</button><button className="btn" type="button" onClick={()=>setEdit(null)}>取消</button></div></form>}
    {candidates.length>0 && <details><summary>上游候选标签 · {candidates.length} 项，需逐项确认</summary><div className="route-tags candidates">{candidates.map((t:Row)=><span className="route-tag" key={t.id}>{t.label}{writable && <><button className="link" onClick={()=>setEdit({...t,state:"confirmed"})}>采用</button><button className="link" onClick={()=>put({...t,state:"excluded"})}>排除</button></>}</span>)}</div></details>}
    {tags.some(t=>t.state==="excluded") && <details><summary>已排除的标签</summary><div className="route-tags">{tags.filter(t=>t.state==="excluded").map(t=><span className="route-tag" key={t.id}>{t.label}{writable && <button className="link" onClick={()=>setEdit({...t,state:"confirmed"})}>重新采用</button>}</span>)}</div></details>}
    {dirty && <div className="stack"><p className="notice">标签修改尚未生效；审批后才用于搜索和客户展示。</p><Field label="标签修改说明"><input className="input" value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></Field><button className="btn primary" disabled={busy || !note.trim() || !!edit} onClick={submit}>提交标签审批</button></div>}{error && <p role="alert" className="notice error">{error}</p>}
  </>;
}

export function RouteEditor({api,id,writable,onProposed}:{api:WarehouseClient;id:string;writable:boolean;onProposed:()=>void}) {
  const state=useData<Row>(api,`/merchant/routes/${id}/content`);
  return <><LoadState {...state}/>{state.data && (isRouteKit(state.data.content)?<RouteKitEditor key={`${id}:${state.data.revision}`} api={api} id={id} initial={state.data} writable={writable} onProposed={onProposed}/>:<ContentForm key={`${id}:${state.data.revision}`} api={api} id={id} initial={state.data} writable={writable} onProposed={onProposed}/>)}</>;
}

function ContentForm({api,id,initial,writable,onProposed}:{api:WarehouseClient;id:string;initial:Row;writable:boolean;onProposed:()=>void}) {
  const [draft,setDraft]=useState<Row>(initial),[content,setContent]=useState<RouteContent>(clone(initial.content)),[dayIndex,setDayIndex]=useState(0),[mode,setMode]=useState("read"),[dirty,setDirty]=useState(false),[note,setNote]=useState(initial.source_note || ""),[checked,setChecked]=useState<string[]>([]),[issues,setIssues]=useState<Row[]>(initial.issues),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[original,setOriginal]=useState(false),[allowed,setAllowed]=useState(true),[preview,setPreview]=useState<Row|null>(null),[evidence,setEvidence]=useState<Row|null>(null),[sourceIndex,setSourceIndex]=useState(0);
  useEffect(()=>{let stopped=false;const controller=new AbortController();let running=false;
    async function check(){if(running)return;running=true;try{const latest=await api.get<Row>(`/merchant/routes/${id}/content`,controller.signal);if(!stopped){setAllowed(true);setDraft(old=>({...old,editing:latest.editing,parsing:latest.parsing}));if(draft.parsing && !latest.parsing)setNotice("附件解析已完成，请重新读取最新候选稿后继续整理。");if(latest.source_changed || latest.revision!==draft.revision)setNotice("云仓内容或来源已有更新。保存时会校验版本，请先保留当前修改并重新读取核对。");}}catch(e){if(!stopped){stopped=true;setAllowed(false);setContent({days:[]} as unknown as RouteContent);setDraft({});setNote("");setIssues([]);setEvidence(null);setOriginal(false);setPreview(null);setError(message(e));}}finally{running=false;}}
    const timer=setInterval(check,30000);window.addEventListener("focus",check);return()=>{stopped=true;controller.abort();clearInterval(timer);window.removeEventListener("focus",check);};
  },[api,id,draft.revision,!!draft.parsing,initial]);
  const day=content.days[dayIndex];
  function update(change:(copy:RouteContent)=>void){const next=clone(content);change(next);setContent(next);setDirty(true);setNotice("");setChecked(old=>old.filter(k=>k!==day?.day_id));}
  function updateDay(change:(copy:Row)=>void){update(next=>change(next.days[dayIndex]));}
  async function save(validate=false){setError("");setBusy(true);try{const result=await api.post<Row>(`/merchant/routes/${id}/content${validate?"/validate":""}`,{expected_revision:draft.revision,expected_source_hash:draft.source_hash,source_kind:draft.source_kind,source_note:note,content,checked_summaries:checked});setIssues(result.issues);if(!validate){setDraft({...draft,revision:result.revision,revision_id:result.revision_id});setContent(result.content);setDirty(false);setChecked([]);setNotice("草稿已保存到云仓，已发布内容未改变。");}else setNotice(result.issues.length?"校验发现以下待处理项。":"结构校验通过；提交前请核对原文事实。" );}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function propose(){setBusy(true);setError("");try{await api.post("/route-content-proposals",{target_id:id,revision_id:draft.revision_id,note});onProposed();}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function source(adopt=false){setBusy(true);setError("");try{const fresh=await api.get<Row>(`/merchant/routes/${id}/content?include_source=true`);setEvidence(fresh);const visibleIndex=mode==="edit"?dayIndex:Number(window.location.hash.match(/itinerary-day-(\d+)/)?.[1]??dayIndex);const visibleDay=content.days[visibleIndex]?.day;setSourceIndex(Math.max(0,(fresh.source_body.days||[]).findIndex((d:Row)=>d.day===visibleDay)));setOriginal(true);if(adopt){setContent(clone(fresh.candidate));setDraft({...fresh,source_kind:fresh.asset_id?"document":"manual"});setDirty(true);setChecked([]);setNotice("已将新候选稿放入编辑区；保存后成为新修订，历史稿继续保留。");}}catch(e){setEvidence(null);setOriginal(false);setError(message(e));}finally{setBusy(false);}}
  async function customer(){setError("");try{setPreview(await api.get<Row>(`/merchant/routes/${id}/customer-preview`));setMode("customer");}catch(e){setError(message(e));}}
  if(isRouteKit(content))return <RouteKitEditor api={api} id={id} initial={{...draft,content,review_resolutions:[]}} writable={writable} onProposed={onProposed}/>;
  if(!allowed)return <p className="notice error" role="alert">当前无法确认内容访问权限，请重新进入线路详情。{error}</p>;
  return <section className="route-workspace stack">
    <div className="route-workspace-head"><div><p className="eyebrow">线路内容工作台</p><h2>把每天的安排说清楚</h2><p className="muted">{draft.revision_id?`已保存草稿 · 第 ${draft.revision} 版`:draft.editing?.status==="complete"?"统一整理稿 · 待人工复核":"解析候选 · 待整理"} · 已发布内容版本 {draft.content_version}{dirty?" · 有未保存修改":""}</p></div><div className="row"><button className={`btn ${mode==="read"?"primary":""}`} onClick={()=>setMode("read")}>阅读行程</button>{writable && <button className={`btn ${mode==="edit"?"primary":""}`} disabled={!!draft.parsing} onClick={()=>setMode("edit")}>整理行程</button>}<button className="btn" onClick={customer}>客户预览</button><button className="btn" disabled={busy} onClick={()=>original?setOriginal(false):source()}>原文对照</button></div></div>
    {draft.parsing && <div className="notice" role="status"><strong>{draft.parsing.status==="failed"?"本次解析未完成":"附件正在重新解析"}</strong><p>{draft.parsing.showing_previous?"当前保留上一代解析供只读对照。新结果不会覆盖人工稿或已发布内容。":"暂未生成可阅读的解析，请等待结果或在文档管理中查看失败原因。"}</p><button className="btn" disabled={busy || dirty} onClick={()=>source(true)}>重新读取最新候选稿</button></div>}
    {draft.editing && <div className="notice"><strong>{draft.editing.status==="complete"?"逐日整理已完成":draft.editing.status==="obsolete"?"来源已变化，本轮整理已停止":"正在后台整理逐日行程"}</strong><p>{draft.editing.status==="complete"?`已通过自动核对 ${draft.editing.edited_days} 天；保留原文待复核 ${draft.editing.retained_days} 项。所有整理稿均需人工复核后发布。`:draft.editing.status==="obsolete"?"请根据当前附件重新解析；历史内容仍保留。":`已处理 ${draft.editing.completed_days} / ${draft.editing.total_days} 天。当前可继续查看行程。`}</p>{draft.editing.status==="complete" && writable && <button className="btn" disabled={busy || dirty} onClick={()=>source(true)}>{draft.revision_id?"对照并采用新整理稿":"读取最新整理稿"}</button>}{dirty && <small>请先保存当前修改，再采用候选稿。</small>}</div>}
    {initial.source_changed && <p className="notice warning">来源已有变化，当前保留的是原草稿。请核对原文后采用新候选稿；不会自动覆盖人工编辑。<button className="btn" disabled={busy} onClick={()=>source(true)}>采用新候选稿</button></p>}
    {error && <p className="notice error" role="alert">{error}</p>}{notice && <p className="notice" role="status">{notice}</p>}
    {original && evidence && <aside className="route-original panel stack" aria-label="原文对照"><div className="row between"><h3>原文与来源记录</h3><button className="btn" onClick={()=>setOriginal(false)}>关闭对照</button></div>{evidence.asset_id && <DocumentEvidence api={api} asset={evidence.asset_id} name={evidence.source_body.source.attachment_name} hash={evidence.source_body.source.etag} version={evidence.asset_product_version} parser={evidence.source_body.source.parser} locations={evidence.source_body.source.page_locations}/>}<p className="muted">以下保留解析原稿；整理稿与原文件分别保存。人工编辑不会改写原文件和页码。</p>{evidence.source_body.days?.length>0 && <><Field label="选择原稿日期"><select className="input" value={sourceIndex} onChange={e=>setSourceIndex(Number(e.target.value))}>{evidence.source_body.days.map((d:Row,i:number)=><option key={i} value={i}>原稿第 {d.day} 天 · {d.title}</option>)}</select></Field><h3>原稿第 {evidence.source_body.days[sourceIndex]?.day} 天 · {evidence.source_body.days[sourceIndex]?.title}</h3><p className="document-prose">{evidence.source_body.days[sourceIndex]?.text}</p></>}{evidence.editing?.reports && <RouteFactReview reports={evidence.editing.reports} onSourceDay={day=>setSourceIndex(Math.max(0,(evidence.source_body.days||[]).findIndex((d:Row)=>d.day===day)))}/>}<details><summary>查看原稿与当前稿差异</summary><DocumentDiff before={evidence.source_body} after={content}/></details><details><summary>查看完整解析原稿</summary><DocumentContent content={evidence.source_body}/></details></aside>}
    {mode==="read" && (!draft.parsing || content.days.length>0) && <RouteItinerary content={content} published={false}/>}
    {mode==="customer" && preview && (preview.published ? <CustomerRoute content={preview.content}/> : <div className="empty panel"><h3>尚无可供客户查看的已发布行程</h3><p>保存草稿后完成内容复核与审批，再在此查看客户展示。</p></div>)}
    {mode==="edit" && !draft.parsing && <>
      <div className="route-editor-grid"><nav className="route-editor-days" aria-label="选择编辑日期">{content.days.map((d,i)=><button key={d.day_id||i} aria-current={i===dayIndex?"step":undefined} onClick={()=>setDayIndex(i)}><strong>D{d.day}</strong><span>{d.title || "标题待补充"}</span></button>)}<button className="btn" onClick={()=>{const n=content.days.length;update(c=>c.days.push(blankDay(n+1)));setDayIndex(n);}}>＋ 添加一天</button></nav>
        <div className="panel stack route-day-form">{day ? <><div className="row between"><h3>第 {day.day} 天</h3><button className="link" onClick={()=>{update(c=>{c.days.splice(dayIndex,1);});setDayIndex(Math.max(0,dayIndex-1));}}>移除此条目</button></div><div className="row"><Field label="行程日序"><input className="input" type="number" min={1} max={100} value={day.day} onChange={e=>updateDay(d=>{d.day=Number(e.target.value);})}/></Field><Field label="当天标题"><input className="input" value={day.title} maxLength={300} onChange={e=>updateDay(d=>{d.title=e.target.value;})}/></Field></div>
          <Field label="参考里程与车程 · 保留原文的距离、时长及对应地点"><textarea className="input" rows={2} value={day.travel_reference||""} maxLength={4000} onChange={e=>updateDay(d=>{d.travel_reference=e.target.value;})}/></Field><Field label="当天简述 · 同时用于简要行程"><textarea className="input" rows={3} value={day.summary||""} maxLength={800} onChange={e=>updateDay(d=>{d.summary=e.target.value;})}/></Field>
          <div className="route-blocks">{(day.blocks||[]).map((block:Row,index:number)=><fieldset className="route-block stack" key={block.block_id}><div className="row between"><Field label={`第 ${index+1} 段类型`}><select className="input" value={block.type} onChange={e=>updateDay(d=>{d.blocks[index].type=e.target.value;})}>{Object.entries(blockNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><div className="row"><button type="button" className="link" disabled={index===0} onClick={()=>updateDay(d=>{[d.blocks[index-1],d.blocks[index]]=[d.blocks[index],d.blocks[index-1]];})}>上移</button><button type="button" className="link" onClick={()=>updateDay(d=>{d.blocks.splice(index,1);})}>删除段落</button></div></div><Field label="段落标题（可选）"><input className="input" value={block.title} maxLength={200} onChange={e=>updateDay(d=>{d.blocks[index].title=e.target.value;})}/></Field><Field label="详细说明 · 请保留自费、外观、替代安排等条件"><textarea className="input" rows={5} value={block.paragraphs.join("\n\n")} onChange={e=>updateDay(d=>{d.blocks[index].paragraphs=e.target.value.split(/\n\s*\n/);})}/></Field>{block.type==="visit" && <div className="row"><Field label="游览方式"><select className="input" value={block.visit_mode} onChange={e=>updateDay(d=>{d.blocks[index].visit_mode=e.target.value;})}>{Object.entries({unknown:"待确认",inside:"入内",outside:"外观",passing:"途经"}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="门票包含情况"><select className="input" value={block.ticket_status} onChange={e=>updateDay(d=>{d.blocks[index].ticket_status=e.target.value;})}>{Object.entries({unknown:"待确认",included:"已含",excluded:"不含"}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field></div>}</fieldset>)}</div><button className="btn" onClick={()=>updateDay(d=>{d.blocks??=[];d.blocks.push({block_id:crypto.randomUUID(),type:"programme",title:"",paragraphs:[""],visit_mode:"unknown",ticket_status:"unknown"});})}>＋ 添加内容段落</button>
          <h3>三餐与住宿</h3><div className="route-meal-form">{[["breakfast","早餐"],["lunch","午餐"],["dinner","晚餐"]].map(([k,label])=><div className="stack" key={k}><Field label={label}><select className="input" value={day.meals?.[k]?.included==null?"unknown":String(day.meals[k].included)} onChange={e=>updateDay(d=>{d.meals[k].included=e.target.value==="unknown"?null:e.target.value==="true";})}><option value="unknown">待确认</option><option value="true">已含</option><option value="false">不含 / 自理</option></select></Field><input className="input" aria-label={`${label}说明`} value={day.meals?.[k]?.text||""} onChange={e=>updateDay(d=>{d.meals[k].text=e.target.value;})}/></div>)}</div>
          <Field label="当晚住宿安排"><select className="input" value={day.overnight} onChange={e=>updateDay(d=>{d.overnight=e.target.value;if(e.target.value==="hotel"&&!d.hotel)d.hotel={name:"",or_similar:false,grade:"",grade_basis:"unknown"};else if(e.target.value!=="hotel"&&e.target.value!=="ship")d.hotel=null;})}>{Object.entries({unknown:"待确认",hotel:"酒店",flight:"飞机上",ship:"船上",home:"返程到家"}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>
          {day.hotel && <div className="stack"><Field label="酒店名称或区域"><input className="input" value={day.hotel.name} onChange={e=>updateDay(d=>{d.hotel.name=e.target.value;})}/></Field><div className="row"><Field label="住宿标准原文"><input className="input" value={day.hotel.grade} onChange={e=>updateDay(d=>{d.hotel.grade=e.target.value;})}/></Field><Field label="标准依据"><select className="input" value={day.hotel.grade_basis||"unknown"} onChange={e=>updateDay(d=>{d.hotel.grade_basis=e.target.value;})}><option value="unknown">待确认</option><option value="supplier_description">供应商描述</option><option value="official_rating">已核验官方评级</option></select></Field></div><label className="check"><input type="checkbox" checked={day.hotel.or_similar} onChange={e=>updateDay(d=>{d.hotel.or_similar=e.target.checked;})}/>原文约定“或同级”</label></div>}
          <label className="check route-brief-check"><input type="checkbox" checked={checked.includes(day.day_id)} onChange={e=>setChecked(old=>e.target.checked?[...old,day.day_id]:old.filter(k=>k!==day.day_id))}/>已核对当天简述与以上详细内容一致</label>
        </> : <p className="empty">添加逐日条目，或从原附件解析候选稿开始整理。</p>}</div>
      </div>
      {day && <DailyExtraFields day={day} onChange={value=>update(next=>{next.days[dayIndex]=value;})}/>}
      {!!content.source.variants?.length && <section className="panel stack"><h3>原文包含多个行程版本</h3><p>选择后请填写适用日期，并保留该版本对应的完整逐日内容。发布后顾问按所选团期读取。</p>{content.source.variants.map(v=><p key={v.start_line}>{v.label} · 原文第 {v.start_line}–{v.end_line} 行</p>)}<Field label="采用的原文版本"><select className="input" value={content.applicability?.version_label||""} onChange={e=>update(next=>{next.applicability={...next.applicability,version_label:e.target.value};})}><option value="">请选择</option>{content.source.variants.map(v=><option key={v.start_line} value={v.label}>{v.label}</option>)}</select></Field></section>}
      <details className="panel"><summary>费用、须知与其他结构字段</summary><DocumentContent content={content} excludeDays onChange={next=>{setContent(next);setDirty(true);setChecked([]);}}/></details>
      {issues.length>0 && <div className="panel route-issues"><h3>最近一次校验 · {issues.length} 项待处理</h3>{issues.map((item,i)=><div className="stack" key={i}><button className="link" onClick={()=>{const match=item.path.match(/^days\/(\d+)/);if(match)setDayIndex(Number(match[1]));}}>{item.message}</button>{item.acknowledgeable && <IssueResolution item={item} onConfirm={reason=>{const next=clone(content);next.quality.resolutions=[...(next.quality.resolutions||[]).filter(r=>r.code!==item.code||r.path!==item.path),{code:item.code,path:item.path,basis_hash:item.basis_hash,note:reason}];setContent(next);setDirty(true);setNotice("已记录原文核对说明，请重新校验并保存草稿。");}}/>}</div>)}</div>}
      <div className="panel stack route-save"><Field label="整理与复核说明"><textarea className="input" rows={2} value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} placeholder="说明核对了哪些原文，哪些内容由人工补充"/></Field><div className="row"><button className="btn primary" disabled={busy||!note.trim()} onClick={()=>save(false)}>保存草稿</button><button className="btn" disabled={busy||!note.trim()} onClick={()=>save(true)}>校验内容</button><button className="btn" disabled={busy||dirty||!draft.revision_id||!note.trim()||issues.length>0} onClick={propose}>提交发布审批</button></div><p className="muted">仅写入云仓。保存草稿不会改变已发布行程，审批通过后才向采购方展示。</p></div>
    </>}
  </section>;
}

function CustomerRoute({content}:{content:Row}) {
  if(isRouteKit(content))return <RouteDetail content={content}/>;
  return <article className="customer-route panel stack" aria-label="客户行程预览"><p className="eyebrow">已发布内容 · 客户视角</p><h1>{content.title}</h1><p>{content.summary.days} 天 · {content.summary.depart_city}</p><div className="route-tags">{content.tags.map((tag:string)=><span className="route-tag" key={tag}>{tag}</span>)}</div>{content.highlights.map((line:string,i:number)=><p key={i}>{line}</p>)}<h2>行程速览</h2>{content.days.map((day:Row)=><p key={day.day}>D{day.day} · {day.summary || day.title}</p>)}{content.days.map((day:Row)=><section className="customer-day stack" key={day.day}><h2>第 {day.day} 天 · {day.title}</h2>{day.summary && day.summary!==day.title && <p className="itinerary-brief">{day.summary}</p>}<DailyTravel day={day}/>{day.blocks.length?day.blocks.map((b:Row,i:number)=><div key={i}>{b.title && <h3>{b.title}</h3>}{b.paragraphs.map((p:string,j:number)=><p className="document-prose" key={j}>{p}</p>)}</div>):<p className="document-prose">{day.text}</p>}<div className="itinerary-meals">{[["breakfast","早餐"],["lunch","午餐"],["dinner","晚餐"]].map(([k,label])=><p key={k}>{label}：{day.meals[k].text || (day.meals[k].included===true?"已含":day.meals[k].included===false?"自理":"待确认")}</p>)}</div><p>住宿：{day.hotel?`${day.hotel.name}${day.hotel.or_similar?"或同级":""}`:({flight:"飞机上",home:"返程到家",ship:"船上"} as Row)[day.overnight]||"待确认"}</p></section>)}<RouteTerms content={content as RouteContent}/></article>;
}

export function RouteContentApproval({api,change,onReady}:{api:WarehouseClient;change:Change;onReady:(ready:boolean)=>void}) {
  const state=useData<Row>(api,`/route-content-revisions/${change.payload.revision_id}`);
  const ready=!!state.data && state.data.product_id===change.payload.target_id && (change.status!=="staged"||state.data.current) && !state.data.issues.length;
  useEffect(()=>{onReady(ready);return()=>onReady(false);},[ready,onReady]);
  return <section className="stack"><LoadState {...state}/>{state.data && <>{!ready && change.status==="staged" && <p className="notice error">草稿或来源已变化，或仍有待处理项，不能应用此审批。</p>}<p>第 {state.data.revision} 次内容修订 · {state.data.source_note}</p>{state.data.asset && <DocumentEvidence api={api} asset={state.data.asset.id} name={state.data.asset.name} hash={state.data.asset.hash} version={state.data.asset.version} parser={state.data.source_body?.source.parser} locations={state.data.source_body?.source.page_locations}/>} {state.data.source_body && <DocumentDiff before={state.data.source_body} after={state.data.body}/>}<RouteItinerary content={state.data.body} published={false}/><RouteTerms content={state.data.body}/><p>发布复核说明：{change.payload.note}</p></>}</section>;
}

function IssueResolution({item,onConfirm}:{item:Row;onConfirm:(note:string)=>void}) {const [reason,setReason]=useState("");return <div className="stack"><Field label="人工核对原文后的处理说明"><input className="input" value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)} placeholder="说明核对了什么，以及采用或保留例外的依据"/></Field><button className="btn" disabled={!reason.trim()} onClick={()=>onConfirm(reason.trim())}>记录已核对此项</button></div>;}
