"use client";
import {useState,type FormEvent} from "react";
import type {Customer,RecordItem} from "./copilot-types";

export default function CopilotMaterialReview({record,customer,busy,run,notify}:{record:RecordItem;customer:Customer|null;busy:boolean;run:(path:string,body?:Record<string,unknown>)=>Promise<any>;notify:(s:string)=>void}){
  const [open,setOpen]=useState(false),[saved,setSaved]=useState(false);
  async function accept(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!customer)return;const data=new FormData(e.currentTarget);const traveler={name:String(data.get("name")),birthday:data.get("birthday")||null,document_type:String(data.get("type")),document_number:String(data.get("number")),document_expiry:data.get("expiry")||null,confirmed:true};
    if(customer.body.travelers.some(t=>t.document_number&&t.document_number===traveler.document_number)){notify("该证件已在客户旅客名单中，请核对现有记录。");return;}
    const result=await run(`/copilot/customers/${customer.id}`,{expected_version:customer.version,customer:{...customer.body,travelers:[...customer.body.travelers,traveler]}});if(result){setSaved(true);setOpen(false);notify("已按你核对的结果保存旅客。");}}
  return <article className="cp-record"><span className="cp-tag">材料识别 · {record.body.status==="review_required"?"待人工核对":"需要手工录入"}</span><p className="cp-muted">{record.body.notice}</p>{(record.body.candidates||[]).map((c:any,n:number)=><div key={n}><p>{c.name||"姓名待核对"} · 证件尾号 {String(c.document_number).slice(-4)}</p><p className="cp-muted">{Object.values(c.checks||{}).every(Boolean)?"格式校验通过，仍需对照原件。":"部分格式校验未通过，请特别核对号码和日期。"}</p>{!saved&&<button disabled={busy||!customer} onClick={()=>setOpen(v=>!v)}>{open?"收起证件信息":"打开核对并编辑"}</button>}{open&&<form onSubmit={accept}><input type="hidden" name="type" value={c.document_type}/><label>姓名<input name="name" required maxLength={100} defaultValue={c.name}/></label><label>出生日期<input name="birthday" type="date" defaultValue={c.birthday||""}/></label><label>证件号<input name="number" required maxLength={80} defaultValue={c.document_number} autoComplete="off"/></label><label>有效期<input name="expiry" type="date" defaultValue={c.document_expiry||""}/></label><label className="cp-check"><input type="checkbox" required/>已逐项对照原件核对，保存为已确认旅客</label><button className="cp-primary" disabled={busy}>采纳核对后的信息</button></form>}{saved&&<p className="cp-notice">本次核对已保存。</p>}</div>)}</article>;
}
