# Copyright 2026 Anthropic PBC
# SPDX-License-Identifier: Apache-2.0

"""``RouteDoc``: one 线路 as a structured document, the static half of the catalog.

The ERP sells a 线路 by name, tags and a Word or PDF attachment; the attachment is where the
product actually is — the flights, the day-by-day programme, the hotels, the meals, what the
price includes and what it does not. ``RouteDoc`` is that attachment read into fields, so the
search can filter on what a line really contains and the cards can show it, while the 团期,
seats and prices stay the ERP's and are read live (``docs/route-doc.md``).

A document is evidence read by a parser, never a schema the agency wrote to, so every one
carries ``source`` (which attachment, which ETag, which parser) and ``quality`` (a completeness
score and the fields a person should look at). The agency's product staff review the flagged
ones; nothing here is published to a customer page before that.

``data/route-schema.json`` is this model's JSON Schema, regenerated by
``scripts/parse_attachments.py --schema`` and held to the model by ``tests/test_route_doc.py``."""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

SCHEMA_VERSION = "1.0"  # Legacy producers remain valid; native producers use 3.0.


class _Doc(BaseModel):
    model_config = ConfigDict(extra="forbid")


class Evidence(_Doc):
    raw: str = ""
    source_lines: list[Annotated[int, Field(strict=True, ge=1)]] = Field(default_factory=list)


class Money(Evidence):
    amount: Decimal | None = Field(default=None, ge=0)
    currency: str = ""
    unit: Literal["person", "room", "night"] | None = None


class Applicability(Evidence):
    start: date | None = None
    end: date | None = None
    departure_cities: list[str] = Field(default_factory=list)
    version_label: str = ""

    @model_validator(mode="after")
    def valid_dates(self):
        if self.start and self.end and self.end < self.start:
            raise ValueError("适用结束日期不得早于开始日期")
        return self


class SourceVariant(_Doc):
    label: str
    start_line: int = Field(ge=1)
    end_line: int = Field(ge=1)

    @model_validator(mode="after")
    def valid_range(self):
        if self.end_line < self.start_line:
            raise ValueError("原文行号范围无效")
        return self


class Formation(Evidence):
    minimum_travelers: int | None = Field(default=None, ge=1)
    failure_action: str = ""
    booking_deadline: str = ""


class CancellationTier(Evidence):
    days_before_min: int | None = Field(default=None, ge=0)
    days_before_max: int | None = Field(default=None, ge=0)
    penalty_percent: Decimal | None = Field(default=None, ge=0, le=100)
    penalty_money: Money | None = None

    @model_validator(mode="after")
    def valid_range(self):
        if (
            self.days_before_min is not None
            and self.days_before_max is not None
            and self.days_before_max < self.days_before_min
        ):
            raise ValueError("退改天数区间无效")
        if self.penalty_percent is not None and self.penalty_money is not None:
            raise ValueError("退改比例与金额不得相互替代或重复确定")
        return self


class PassengerRule(Evidence):
    minimum_age: int | None = Field(default=None, ge=0, le=120)
    maximum_age: int | None = Field(default=None, ge=0, le=120)
    bed_policy: str = ""
    conditions: str = ""


class VisaRule(Evidence):
    type: Literal["schengen", "electronic", "on_arrival", "exempt"] | None = None
    submission_deadline: str = ""
    passport_validity: str = ""


class Insurance(Evidence):
    included: bool | None = None
    description: str = ""


class TravelerRequirements(_Doc):
    child: PassengerRule = Field(default_factory=PassengerRule)
    senior: PassengerRule = Field(default_factory=PassengerRule)
    pregnancy: Evidence = Field(default_factory=Evidence)
    visa: VisaRule = Field(default_factory=VisaRule)
    insurance: Insurance = Field(default_factory=Insurance)


class Meeting(Evidence):
    location: str = ""
    time: str = ""
    domestic_connection: str = ""


class ReviewResolution(_Doc):
    code: str
    path: str
    basis_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    note: str = Field(min_length=1, max_length=1000)


class Flight(_Doc):
    """One flight segment as the attachment writes it (参考航班 MU6017 上海浦东-科伦坡 1425-1900).
    Times are kept as written — an attachment states 夏令时/冬令时 pairs and ``+1`` days — and
    ``day`` is the itinerary day the segment is on."""

    day: int
    flight_no: str = ""
    carrier: str = ""
    from_place: str = ""
    to_place: str = ""
    times: str = ""
    raw: str
    departure_local_time: str | None = None
    arrival_local_time: str | None = None
    arrival_day_offset: int | None = Field(default=None, ge=0, le=3)


class Sight(_Doc):
    """One named stop of a day: a 【景点】, a 购物店, a 自费项目 or a 赠送 item. ``kind`` is
    what the words around it say; ``ticket_included`` follows explicit fee statements. Visiting inside or outside
    does not establish whether a ticket is included."""

    name: str
    kind: Literal["景点", "外观", "购物", "自费", "赠送", "自由活动"] = "景点"
    duration: str = ""
    ticket_included: bool | None = None
    raw: str = ""


class Meal(_Doc):
    """An explicit meal statement; an empty cell remains unknown."""

    text: str = ""
    included: bool | None = None


class Meals(_Doc):
    breakfast: Meal = Field(default_factory=Meal)
    lunch: Meal = Field(default_factory=Meal)
    dinner: Meal = Field(default_factory=Meal)


class Hotel(_Doc):
    """The night's 住宿: the names as written (several alternatives joined by ``/``), whether
    the attachment says 或同级, and the standard where a grade is stated on the line."""

    name: str
    or_similar: bool = False
    grade: str = ""
    grade_basis: Literal["supplier_description", "official_rating", "unknown"] = "unknown"
    room_type: str | None = None
    consecutive_nights: int | None = Field(default=None, ge=1)
    raw: str = ""


class ItineraryBlock(_Doc):
    """Ordered presentation content. Evidence remains in the immutable original parse."""

    block_id: str = Field(min_length=1, max_length=80)
    type: Literal[
        "programme", "transport", "visit", "free_time", "shopping", "optional", "notice"
    ] = "programme"
    title: str = Field(default="", max_length=200)
    paragraphs: list[str] = Field(default_factory=list, max_length=100)
    visit_mode: Literal["inside", "outside", "passing", "unknown"] = "unknown"
    ticket_status: Literal["included", "excluded", "unknown"] = "unknown"


class Day(_Doc):
    """One itinerary day. ``places`` is the title's A-B-C route; ``distances_km`` the KM
    figures written between them; ``transport`` the 车程/交通 notes; ``text`` the programme
    as written, kept whole because the parsed fields are a reading of it and not a
    replacement."""

    day: int
    title: str
    places: list[str] = Field(default_factory=list)
    distances_km: list[int] = Field(default_factory=list)
    transport: str = ""
    travel_reference: str = Field(default="", max_length=4000)
    countries: list[str] = Field(default_factory=list)
    cities: list[str] = Field(default_factory=list)
    location_raw: str = ""
    vehicle_type: str | None = None
    vehicle_raw: str = ""
    overnight: Literal["hotel", "ship", "flight", "home", "unknown"] = "unknown"
    flights: list[Flight] = Field(default_factory=list)
    sights: list[Sight] = Field(default_factory=list)
    meals: Meals = Field(default_factory=Meals)
    hotel: Hotel | None = None
    text: str = ""
    day_id: str = Field(default="", max_length=80)
    summary: str = Field(default="", max_length=800)
    blocks: list[ItineraryBlock] = Field(default_factory=list, max_length=150)
    # The brief and detailed view refer to the same reviewed programme. A body
    # edit invalidates this digest until the operator explicitly rechecks the brief.
    summary_basis_hash: str = ""


class ShoppingStop(_Doc):
    name: str
    day: int | None = None
    duration: str = ""
    categories: list[str] = Field(default_factory=list)
    raw: str = ""


class OptionalItem(_Doc):
    """A 自费项目 with the price as written (``120 美金/人``)."""

    name: str
    price: str = ""
    day: int | None = None
    money: Money = Field(default_factory=Money)
    raw: str = ""


class Policies(_Doc):
    """What the terms say about money and paperwork, each the sentence as written."""

    single_room: str = ""
    child: str = ""
    visa: str = ""
    cancellation: str = ""
    deposit: str = ""


class Summary(_Doc):
    days: int
    nights: int | None = None
    depart_city: str = ""
    countries: list[str] = Field(default_factory=list)
    region: str = ""


class Cover(_Doc):
    """The attachment's front matter: the labelled rows (航空公司, 酒店标准, 用餐安排, 吃/住/行)
    and the ★ highlights, as written."""

    airline: str = ""
    hotel_standard: str = ""
    meal_standard: str = ""
    highlights: list[str] = Field(default_factory=list)
    fields: dict[str, str] = Field(default_factory=dict)


class PageLocation(_Doc):
    """Physical PDF pages of a parsed source block, not proof of every derived field.

    Day numbering refers to the original parse. Human revisions do not move these
    locators. DOCX and historical parses without location evidence leave them absent.
    """

    section: Literal["cover", "itinerary", "terms"]
    day: Annotated[int, Field(strict=True, ge=1)] | None = None
    pages: list[Annotated[int, Field(strict=True, ge=1)]] = Field(min_length=1)

    @model_validator(mode="after")
    def valid_location(self):
        if (self.section == "itinerary") != (self.day is not None):
            raise ValueError("Only itinerary locations must name a day")
        if self.pages != sorted(set(self.pages)):
            raise ValueError("Pages must be unique and ascending")
        return self


class Source(_Doc):
    attachment_name: str
    attachment_url: str
    etag: str | None = None
    bytes: int
    parsed_at: datetime | None
    parser: str
    page_locations: list[PageLocation] = Field(default_factory=list)
    unread_image_pages: list[Annotated[int, Field(strict=True, ge=1)]] = Field(default_factory=list)
    lines: list[str] = Field(default_factory=list, max_length=15000)
    variants: list[SourceVariant] = Field(default_factory=list, max_length=100)
    overview_meals: dict[str, Meals] = Field(default_factory=dict)
    extraction_method: Literal["native", "mineru", "hybrid"] = "native"
    extraction_hash: str = Field(default="", pattern=r"^(?:[a-f0-9]{64})?$")


class Quality(_Doc):
    """``completeness`` is the parser's own score in [0, 1] (``route_parser.score``);
    ``needs_review`` names what a person should check, in the reviewer's language;
    ``reviewed_by``/``reviewed_at`` are set by the reviewer, never by the parser."""

    completeness: float = Field(ge=0, le=1)
    needs_review: list[str] = Field(default_factory=list)
    reviewed_by: str = ""
    reviewed_at: datetime | None = None
    resolutions: list[ReviewResolution] = Field(default_factory=list, max_length=200)


class RouteDoc(_Doc):
    """One 线路 as its attachment describes it. Identity and the fields the ERP itself states
    come from the catalog record; everything under ``cover``, ``days`` and the terms comes
    from the attachment."""

    schema_version: Literal["1.0", "2.0", "3.0"] = SCHEMA_VERSION
    route_id: int
    route_code: str
    name: str
    department: str
    sale_type: str = ""
    # The 线路 this document was reviewed as, where this line is the same product sold under a
    # second name: its 行程 is that line's word for word, so the reviewed document is read
    # under this line's own identity (``route_docs.py``). ``None`` on a document read from its
    # own attachment, which is every document the parser writes.
    twin_of: int | None = None
    summary: Summary
    cover: Cover = Field(default_factory=Cover)
    transport: list[Flight] = Field(default_factory=list)
    days: list[Day] = Field(default_factory=list)
    inclusions: list[str] = Field(default_factory=list)
    exclusions: list[str] = Field(default_factory=list)
    shopping: list[ShoppingStop] = Field(default_factory=list)
    optional: list[OptionalItem] = Field(default_factory=list)
    policies: Policies = Field(default_factory=Policies)
    notices: list[str] = Field(default_factory=list)
    applicability: Applicability = Field(default_factory=Applicability)
    formation: Formation = Field(default_factory=Formation)
    service_fee: Money = Field(default_factory=Money)
    single_room_supplement: Money = Field(default_factory=Money)
    cancellation_tiers: list[CancellationTier] = Field(default_factory=list)
    traveler_requirements: TravelerRequirements = Field(default_factory=TravelerRequirements)
    meeting: Meeting = Field(default_factory=Meeting)
    shopping_total: int | None = Field(default=None, ge=0)
    source: Source
    quality: Quality


def json_schema() -> dict:
    """The JSON Schema the agency's product staff and the review tooling read."""
    schema = RouteDoc.model_json_schema()
    schema["title"] = "RouteDoc"
    schema["$comment"] = (
        f"schema_version {SCHEMA_VERSION}; one 线路 as its 行程附件 describes it, parsed by "
        "examples/tour/api/route_parser.py. Fields under source and quality are the parser's own."
    )
    return schema
